#!/bin/sh

if [ ! -e "$HOME"/.doom3/darkmod ] ;then
   mkdir -p "$HOME"/.doom3/darkmod/
   cp -r /usr/lib/thedarkmod/* "$HOME"/.doom3/darkmod/
fi

cd "$HOME"/.doom3/darkmod/
xterm -e sh tdm_update_updater.sh && ./thedarkmod.x86 "$@"